services:
  fastapi:
    container_name: backend
    build:
      context: backend/.
      dockerfile: Dockerfile
    env_file:
      - backend/.env.local
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"